let x1;
let x2;
let y1;
let y2;
let d;
console.log("digite o valor do ponto x:");
x1();
x2();
console.log("digite o valor da localização do ponto y:");
y1();
y2();
d = Math.sqrt(Math.pow(x2 - x1,2) + Math.pow(y2 - y1,2));
console.log("a distancia entre os pontos é: ", d);
