let raio;
let h;
let pi = 3.14;
let at;
console.log("digite o raio do cilindro: ");
raio();
console.log("digite a altura do cilindro: ");
h();
at = 2*pi*raio*(raio + h );
console.log("a area do cilindro é ", at);
